FROM node:14-alpine

WORKDIR /usr/app

COPY ./package.json ./

# Clean npm cache and install with verbose logging
RUN npm cache clean --force && npm install --verbose

COPY ./ ./

CMD ["npm", "run", "start"]

